### ISSUE TITLE
change handle signature

### ISSUE THREAD

**Issue by derickbailey** [arobson/rabbot#1]
since we're in breaking-changes mode with this library, what would you think about changing the `handle` function signature?

```js
var handlerOptions = {
  queue: "some.q",
  messageType: "some.type"
};

rabbot.handle(handlerOptions, function(){ ... });
```

it would be easy to preserve compatibility with the existing API by checking the first param to see if it's a string for messageType vs an object for more configuration.

**Comment by arobson** [comment]
@derickbailey yeah, I like it. Let me see if I can get this change in soon and I'll ping you in the thread again when it's in place.

**Comment by arobson** [comment]
@derickbailey ok, 1.0.0-9 has this now. Check the README to see the options and how it works: https://github.com/arobson/rabbot#options
