### ISSUE TITLE
Support reply array

### ISSUE THREAD

**Issue by swarthy** [arobson/rabbot#105]
When I try to reply `Array` I get `Error: Cannot serialize unknown data type`

Seems like `getContentType` in reply [https://github.com/arobson/rabbot/blob/master/src/amqp/queue.js#L72](https://github.com/arobson/rabbot/blob/master/src/amqp/queue.js#L72) returns `application/octet-stream` for array (meanwhile [https://github.com/arobson/rabbot/blob/master/src/amqp/exchange.js#L52](https://github.com/arobson/rabbot/blob/master/src/amqp/exchange.js#L52) array handles correctly)
Should I open PR or it will be fixed in v2?

**Comment by swarthy** [comment]
May be it should return `application/json` for numbers and `null` by default?
With current behaviour there is no way to send number or null in body, I need check body manually for it and setup `contentType` in options.

**Comment by arobson** [comment]
@swarthy - if you want to publish an octet-stream without having to specify that that's what you're doing, using `contentType`, you can publish a `Buffer`.

See: https://github.com/arobson/rabbot/blob/master/docs/publishing.md#rabbotpublish-exchangename-options-connectionname-
