### ISSUE TITLE
Multiple Connections with JSON configuration

### ISSUE THREAD

**Issue by felixheck** [arobson/rabbot#114]
Hi there!

I‘m currently thinking about replacing amqplib with rabbit and was wondering what’s the best way to handle multiple connections (different rabbitmqs) with the JSON config? Just calling `configure` multiple times with the different configuration objects?😊 

Thanks a lot!

**Comment by luddd3** [comment]
I don't think rabbit would be a good fit for that. Also, consider that the maintainer haven't had any activity in about six months.

**Comment by felixheck** [comment]
@luddd3 What’s your suggestion/recommendation for easy to set up, high performance and flexible amqp lib?

**Comment by luddd3** [comment]
I would write a thin wrapper around amqplib or use something based on it with active development. Currently I use rabbit for some projects, but I would be hesitant to recommend it to new users.

**Comment by felixheck** [comment]
@luddd3 Tried [amqplib-easy](https://github.com/lanetix/node-lanetix-amqp-easy) but it's performance is horrible. It just handles up to 1500 msg/s...rabbot up to 14000 msg/s.

And I don't wanna reinvent the wheel.
So if there're any existing high performance wrappers with active maintenance, let me know :)

**Comment by luddd3** [comment]
Ok, I don't know if that lib does something special to kill performance, but I would expect them to be similar since both rabbit and amqplib-easy depend on amqplib to handle the communication with rabbitmq.

**Comment by arobson** [comment]
@felixheck - yep, just use multiple configure calls - you'll get a different promise for each. Since each connection and follow up set of topology operations is a stack of promises, I think you'll be happier treating each as a separate configure call.

Version 2 is out now and I hope to publish some follow up changes later today or tomorrow to address outstanding issues/requests.
