### ISSUE TITLE
Logging mistake in config.js?

### ISSUE THREAD

**Issue by dfischer0** [arobson/rabbot#12]
In file config.js, you create a log variable and use it to log errors. But you also create a logger variable and... never use it. Is that normal?

var log = require( "./log" )( "rabbot.configuration" );
[...]
var logger;
module.exports = function( Broker ) {
	Broker.prototype.configure = function( config ) {
		if( !logger && config.logging ) {
			logger = require( "./log" )( config.logging || {} );
		}
[...]

Also, the documentation doesn't mention logging at all, and in particular how to enable it. Is it compatible with bunyan?

David

**Comment by arobson** [comment]
@dfischer0 - Logging uses whistlepunk. The weird log/logging thing in config.js has to do with a whistlepunk defect which I'm not 100% sure is resolved and I'll have to revisit at another time. I've added a short example to the README about logging.

Whistlepunk adapters are very simple to write and you should be able to write a bridge to bunyan in your project and use it as an adapter. As an example, here's a mock adapter used in Whistlepunk's : [https://github.com/LeanKit-Labs/whistlepunk/blob/master/spec/adapters/mockAdapter.js](specs) and you can see it being used in the config block: [https://github.com/LeanKit-Labs/whistlepunk/blob/master/spec/behavior/log.spec.js#L35](here).
