### ISSUE TITLE
Is this still under development?

### ISSUE THREAD

**Issue by jorgecuesta** [arobson/rabbot#124]
Hi all, someone know if this is still under development? because see a lots of issues and pr and lot of time of last commit.

**Comment by arobson** [comment]
Hi @jorgecuesta - I am close to having the version 2 completed. The tests are currently broken for 6 due to a breaking change in a dependency that is not easily resolved. I'll leave this open for now since I can't publish it yet, but you can look at the v2 branch if interested.

**Comment by arobson** [comment]
Just following up - version 2 is out and I'm working on a follow up to address some additional requests / issues.
