### ISSUE TITLE
Rabbot supports setting maxPriorities on queues but not setting priority on a message

### ISSUE THREAD

**Issue by dfischer0** [arobson/rabbot#13]
I didn't find any way to publish a message with a priority. Did I miss something?

**Comment by arobson** [comment]
@dfischer0 - there isn't a way to do this. I'm actually not interested in adding this feature. As a general rule, I avoid using message priorities. I'm up for accepting a PR with the feature if you're interested in adding it. It would need to include test coverage and a description for how to use it in the README.md.

**Comment by dfischer0** [comment]
@arobson - fair enough, by why do you then offer a "maxPriorities" option on queues? ;)

**Comment by arobson** [comment]
@dfischer0 - If you declare or even assert an AMQP exchange or queue with different configuration than what exists, Rabbit will kill the channel on you and it's game over :\ That means if you were to try and use rabbot with a system that had queues where features were in place that rabbot didn't support, it'd never start up. Still seem arbitrary to you? You can fix it with a PR! 😄 

But seriously, not only do I think messaging priority is dangerous, it's poorly specified by the AMQP protocol and its implementation in Rabbit will lead to unpredictability or odd behaviors under certain circumstances. One of the goals I have for rabbot is that it makes messaging easier to implement and more predictable; introducing priorities without a great deal of integration testing and documentation goes against those goals. I hope you can understand that I'm not up for taking on that amount of effort for a feature I don't believe is necessary and puts the goals of the library at risk.

If you'd like to talk about the kinds of high level use cases you'd like to solve for using priorities, I'd be happy to discuss alternative solutions.
