### ISSUE TITLE
cleanup docker container after kill

### ISSUE THREAD

**Issue by alonisser** [arobson/rabbot#130]
On dev:

Currently running
```bash

npm run start-container
npm run stop-container

npm run start-container # (again)
```
Would fail the second run since kill does not clean the existing container
A cleanup should remove container after kill

**Comment by arobson** [comment]
@alonisser - just a heads up that I did make a slight change after accepting your PR. Calling a command named `stop-container` and having it removed could be really irritating to someone who was expecting to be able to start it back up.

I updated the section in `HOW_TO_CONTRIBUTE` to show the changed [commands]( https://github.com/arobson/rabbot/blob/master/HOW_TO_CONTRIBUTE.md#included-docker-container). I also added a `bootstrap-container` to go along with the same line of thinking.

Thanks!
