### ISSUE TITLE
Custom arguments support

### ISSUE THREAD

**Issue by nhanle92** [arobson/rabbot#151]
Hi,
I want to add some custom arguments into queues like `x-queue-mode` and custom type `x-delayed-message` into the exchange. How could I do this?

**Comment by nhanle92** [comment]
I found out that I could do this normally by set `arguments: {}` like what I did in amqplib.

**Comment by manuel-reil** [comment]
@nhanledev Cool, where have you put the arguments object? I am also interested in using the delay message exchange type. Have you added it in the exchange JSON config?
