### ISSUE TITLE
Feature Request: sendToQueue

### ISSUE THREAD

**Issue by rg1220** [arobson/rabbot#18]
I may end up working on this but the feature request is to implement a `sendToQueue` function that should work just like the publish function except it'll go to whatever queue you send the message to. So instead of relying on the routingKey you can have it sent directly to a queue.

Documentation for sendToQueue
http://www.squaremobius.net/amqp.node/channel_api.html#channel_sendToQueue

**Comment by arobson** [comment]
@rg1220 can I ask why you want to send to queues directly? Rabbot only uses this feature to implement the request/response pattern in order to send to specific end points. Rabbit/AMQP/rabbot are over-kill if your primary use case is sending messages directly to a specific queue.

**Comment by rg1220** [comment]
I was looking to do a per-worker response queue that I can then handle the messages myself rather than replying on using rabbot requests. I'm still using much of Rabbot's functionality.

However, after thinking about it some more, I could do named queues with bindings and just use a routing key to go to the correct response queue. I figured sendToQueue was probably more efficient than using a routingKey.

**Comment by derickbailey** [comment]
when you send to queue, you are publishing through an exchange and exchanges require a routing key. 

the exchange happens to be a special, built-in exchange, but it's still an exchange. 

this specialized exchange receives the queue name as the routing key, and uses that to route the message through the exchange and to the correct queue.

send to queue is useful when you are doing replies and a few other very specific scenarios. but in general, i considered it an anti-pattern that just makes demo code look easier. 

it's a rather deceptive implementation that caused me a lot of confusion when i first started learning RMQ.

**Comment by shawnHartsell** [comment]
In addition to what @derickbailey  said....in RabbitMQ all messages route through some kind of exchange. You use a direct exchanges to achieve your use case @rg1220 

The built-in default exchange is a direct exchange. Additionally, every queue that is created is automatically bound to the direct exchange with the routing key of the queue name. This means that if you publish a message to the default exchange and use your destination queue as the routing key, it will be delivered to that queue.

https://www.rabbitmq.com/tutorials/amqp-concepts.html

**Comment by rg1220** [comment]
@shawnHartsell, @derickbailey: Thanks guys, that really helps to clarify how it all works. And based on my use case I need to be using a direct exchange to get the data back to the API worker. I could do so using either a new direct exchange or by using the default exchange and using the queue name as the routing key. In which case I don't need to use sendToQueue because I should be able to specify my new direct exchange (or use `""`) with the queue name as the routingKey to get my message back to the API worker.

---------------------------

Additional info on use-case:
The idea is I have an API worker which receives HTTP requests. It holds onto that request handle until it eventually gets a response back from "the system". The API worker publishes a message with a routingKey based on the path.  Worker X will pick it up, does some work and either publishes back to the API worker or sends the message to another worker. If sent to another worker then worker Y pick it up, do some work and will publish back to the API worker with the data to send to the client.

I've been trying to avoid using Rabbot requests as I've had issues with duplicate messages being created because a worker down the "request chain" (Worker A requests Worker B, Worker B requests Worker C, etc) restarted before all message responses have been propagated back down to the original request. Using a "publish chain" can still cause something similar, but with fewer duplicated messages. This also gives the system the ability to short cut a message directly back to the API worker without doing replies to each worker before it gets back.
