### ISSUE TITLE
Cannot publish array

### ISSUE THREAD

**Issue by Cyri-L** [arobson/rabbot#19]
Hi, 

Why did you explicitly refuse an array as "application/json" type ?

```js

function getContentType( message ) {
	if( message.contentType ) {
		return message.contentType;
	}
	else if( _.isString( message.body ) ) {
		return "text/plain";
	} else if( _.isObject( message.body ) && !message.body.length ) { //why ?
		return "application/json";
	} else {
		return "application/octet-stream";
	}
}
```

Thanks !!

**Comment by arobson** [comment]
@Cyri-L the intent is an array would be treated as an octet stream instead. I haven't run across any cases where I wanted to encode a raw array alone as JSON. It's a trivial matter to assign the array to a property: 
```json
{ "list": [ 100, 101, 200, 201 ] }
```
So sending it like this:
```js
rabbot.publish( "some-ex", { type: "my-message", body: { list: [ 1, 2, 3, 4 ] } } );
```
Should solve the issue without requiring a breaking change.

**Comment by brandonpsmith** [comment]
You can do this by explicitly setting the message contentType to 'application/json' and pass an array as the message body. I would like to see a buffer as the message body to represent the application/octet-stream type. This would create breaking change though.

```javascript
function getContentType( message ) {
    if( message.contentType ) {
        return message.contentType;
    }
    else if( _.isString( message.body ) ) {
        return "text/plain";
    } else if( _.isObject( message.body ) || _.isArray( message.body ) ) { //why ?
        return "application/json";
    } else if (Buffer.isBuffer( message.body ) ) {
        return "application/octet-stream";
    }
}

rabbit.publish( "exchange",  {
    contentType: "application/octet-stream",
    body: Buffer.from([0x62,0x75,0x66,0x66,0x65,0x72]) //['b','u','f','f','e','r']
});
```

**Comment by arobson** [comment]
@brandonpsmith I can see making a change to have rabbot detect Buffers so that you don't have to specify octet-stream when one is provided, but I still don't see any reason to change things so that sending a plain array should default to JSON when the behavior I listed in the previous comment gets you this behavior with 0 code changes.
