### ISSUE TITLE
Vulnerabilities in Dependenciens

### ISSUE THREAD

**Issue by Ibrahimtrrc** [arobson/rabbot#195]
When you install rabbot ( npm install rabbot ) you will have 6 vulnerabilities ( 3 low, 3 moderate ).
Here is the result of npm audit:
`  Moderate        Prototype Pollution                                           
                                                                                
  Package         lodash                                                        
                                                                                
  Patched in      >=4.17.11                                                     
                                                                                
  Dependency of   rabbot                                                        
                                                                                
  Path            rabbot > machina > lodash                                     
                                                                                
  More info       https://npmjs.com/advisories/782                              
                                                                                
                                                                                
  Moderate        Prototype Pollution                                           
                                                                                
  Package         lodash                                                        
                                                                                
  Patched in      >=4.17.11                                                     
                                                                                
  Dependency of   rabbot                                                        
                                                                                
  Path            rabbot > monologue.js > lodash                                
                                                                                
  More info       https://npmjs.com/advisories/782                              
                                                                                
                                                                                
  Moderate        Prototype Pollution                                           
                                                                                
  Package         lodash                                                        
                                                                                
  Patched in      >=4.17.11                                                     
                                                                                
  Dependency of   rabbot                                                        
                                                                                
  Path            rabbot > monologue.js > riveter > lodash                      
                                                                                
  More info       https://npmjs.com/advisories/782                              
                                                                                
                                                                                
  Low             Prototype Pollution                                           
                                                                                
  Package         lodash                                                        
                                                                                
  Patched in      >=4.17.5                                                      
                                                                                
  Dependency of   rabbot                                                        
                                                                                
  Path            rabbot > machina > lodash                                     
                                                                                
  More info       https://npmjs.com/advisories/577                              
                                                                                
                                                                                
  Low             Prototype Pollution                                           
                                                                                
  Package         lodash                                                        
                                                                                
  Patched in      >=4.17.5                                                      
                                                                                
  Dependency of   rabbot                                                        
                                                                                
  Path            rabbot > monologue.js > lodash                                
                                                                                
  More info       https://npmjs.com/advisories/577                              
                                                                                
                                                                                
  Low             Prototype Pollution                                           
                                                                                
  Package         lodash                                                        
                                                                                
  Patched in      >=4.17.5                                                      
                                                                                
  Dependency of   rabbot                                                        
                                                                                
  Path            rabbot > monologue.js > riveter > lodash                      
                                                                                
  More info       https://npmjs.com/advisories/577                              
                                                                                
found 6 vulnerabilities (3 low, 3 moderate) in 33 scanned packages
  6 vulnerabilities require manual review. See the full report for details.`

**Comment by Ibrahimtrrc** [comment]
This is not maintained anymore right ?

**Comment by djMax** [comment]
It does not appear to be. But we are still users of it. So I suppose I should consider forking it.

**Comment by doubliez** [comment]
Same here, we are using this library and need to have these vulnerabilities fixed. Will probably fork it too if this is truly not maintained anymore.

**Comment by zlintz** [comment]
I am starting this process of a forked version and plan to maintain if interested in see 
https://github.com/zlintz/foo-foo-mq

**Comment by zlintz** [comment]
I have released a verse of this with the vulnerabilities dependencies address.
https://github.com/Foo-Foo-MQ/foo-foo-mq

**Comment by arobson** [comment]
hi @zlintz - thanks for forking this and continuing to keep it working for folks who would like to use this. I've marked this repo as deprecated and directed folks your way. 💯

**Comment by zlintz** [comment]
Thank you @arobson, if you would like to stay involved please let me know.
