### ISSUE TITLE
bind to a queue without a message type

### ISSUE THREAD

**Issue by derickbailey** [arobson/rabbot#2]
as a side effect of #1, i would like to be able to specify a queue without a message type, when handling a message. 

it's good that we can specify the queue, now. with that, the message type doesn't make much sense anymore. 

```js
var opts = {
  queue: "some.q"
};
rabbot.handle(ops, function(){ ... });
```

i could, for now, just subscribe to `"#"` for the message type, when combined with a queue, but it would be nice to not have to specify the message type.

**Comment by arobson** [comment]
@derickbailey if I were implementing the options, I could just always default type to `#`. There's not really another way for me to get messages to the handler.

**Comment by derickbailey** [comment]
> There's not really another way for me to get messages to the handler.

well... there is, but it involves the removal of postal and going straight to the amqplib handler functions.

if postal is using the type as it's internal subscription, wouldn't a type of `#` give me all messages published through that postal instance? i haven't looked through the code in some time, so i'm probably not remembering how postal is setup, correctly

**Comment by arobson** [comment]
@derickbailey - ok, I've updated the handle call to take an options hash. You shouldn't have to specify a type if you want to handle everything arriving on the queue.
