### ISSUE TITLE
addQueue() - how to retrieve generated "uniqueName" ?

### ISSUE THREAD

**Issue by iamjochem** [arobson/rabbot#26]
hi there,

I'm trying figure out how to determine the generated queue name after a all to `addQueue()` so that I can add a binding, handler & subscription to that queue! I am not exactly sure what the Promise returned by `addQueue()` is supposed to resolve to but the object I get doesn't contain the name of the queue I just created anywhere in it's [deeply] nested structure ... I am doing something like so:

```js
rabbit.addQueue('logview', {
        autoDelete : true,
        durable    : false,
        exclusive  : true,
        noAck      : true,
        noBatch    : true, // TODO: set FALSE here for better performance?
        messageTtl : 10000,
        unique     : 'id'
}).then( console.log );
```

inside the guts of **rabbot** the generated queue name is stored as part of the queue options (key is `uniqueName`) and you can extract this info like so:

```js
var my_queue_alias = 'logview';
Object.keys(rabbot.connections.default.definitions.queues[ my_queue_alias ].uniqueName);
```
**BUT** getting at the generated name this way is very wrong (a couple of [SOLID principles](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) cry at the thought of me digging into `rabbot.connections`)) ... do you agree that consumers of the **rabbot** module  should "stay-the-f\*\*\*-out" of **rabbot's** internals? if so could you tell me what the correct way is to retrieve the generated queue name.

thanks!

> PS - I new to AMQ, RabbitMQ and **rabbot** ... be gentle please :-)

> PPS - AFAICT **wascally** does not offer this "generate a unique queue name" functionality ... maybe this is something new to **rabbot** that nobody has used yet?

**Comment by arobson** [comment]
@iamjochem - your instincts are correct - you shouldn't have to know how to get at the internals. There's a chance that rabbot has a defect, but the idea here is that when rabbot adds things to the queue name for you, your code can still keep using the alias you provided for the queue name when providing bindings and starting the subscription. I _thought_ we were using that behavior here at LeanKit, but I'll have to check.

If that's not the case, I'll need to add test coverage and fix the defect. Please try that first by just using `"logview"` as the queue name and see if rabbot doesn't handle the fact that the underlying name isn't different for you behind the scenes.

**Comment by iamjochem** [comment]
@arobson - sorry I forgot to mention it ... using the alias "logview" was the first thing I tried, that didn't work I'm afraid, I get `debug()` output like so:

```
rabbot.topology info +15ms Binding queue 'logview' to 'oo.logs' on 'default' with keys: ["#"]
rabbot.io error +5ms Error emitted by channel 'control' - 'Error: Channel closed by server: 404 (NOT-FOUND) with message "NOT_FOUND - no queue 'logview' in vhost '/'"
```

> **off topic**: it might be nice to publically expose the generated/underlying name - this would allow exporting of the name for use in other processes or [node] modules.

**Comment by arobson** [comment]
@iamjochem ok, 1.0.3 will fix the bindQueue problem you are having above. I was able to call start subscription on the queue by the "friendly name" I provided. You can get to the unique name generated for the queue but you shouldn't have to and I'd rather make it so you shouldn't want to. Publishing directly to queues is discouraged so really you should just be:
 1. adding queues
 2. binding queues
 3. starting subscriptions

In very, very rare cases, you might need to stop subscriptions and remove queues, but that's pretty advanced. In most cases you should declare all of your service's topology up front, at once as part of the configure call and leave it in place. I've rarely seen a good case for services that need to be constantly mutating the topology over their lifecycle.

Let me know if you'd like to discuss use cases. I might be able to help you design something that meets your needs and keeps things easy to manage.

**Comment by iamjochem** [comment]
@arobson - I concur, v1.0.3 fixes the `bindQueue()` and `startSubscription()` problem with regard to using "queue aliases" - thanks for taking the time to look into this and get a fix out!

this particular use case was a bit of an edge case (I will be using a predefined 'base' topology in my apps/processes) ... I have written a shellscript that creates an exclusive queue for the duration of the process that is bound to a "log" topic-exchange, the script just dumps the log items to STDOUT ... it's the distributed AMQ equivalent off `tail -f /var/log/some-app.log` ... when the script dies the queue is no longer needed (there is a "real" queue that persists messages sent to the "log" exchange, a seperate consumer is responsible for eating those messages and pumping them into elasticsearch)

maybe that is a completely stupid way of handling 'platform-wide' logging - I'm still learning to walk in AMQ-land ... probably be back here with more noob-problems soon enough ;-)
