### ISSUE TITLE
addQueue().then() - Promise rejected if no ready connection, but queue created later

### ISSUE THREAD

**Issue by iamjochem** [arobson/rabbot#27]
hi there (me again, sorry!),

>  VERSION INFO: **node v6.2.2**, **rabbot v1.0.2**

I am calling `rabbot.addQueue()`, and I noticed that the promise it returns will be rejected if the connection is not available (error message is "*Failed to create queue 'logview' on connection 'default' with 'No endpoints could be reached'*") but a little later (once rabbot has aquired a connection) the queue is actually created (presumably due to "retries"). It seems the `addQueue()` promise is resolved/rejected based on the first attempt to create the queue, I would have assumed that it would be resolved/rejected based on the last attempt to create it.

### a repro-script
the very low `timeout` value makes the bad magic happen (I happened upon all this because I mistakenly assumed `timeout` was a value in seconds!) ... you may need to tweak to the value of `timeout` in order to trigger the reproduce-case:

```js
// get rabbot to output debug messages
process.env.DEBUG="rabbot.*";

var rabbot  = require('rabbot');

var options = {
    connection : {
        uri               : 'amqp://localhost:5672',
        timeout           : 5, // NB: you might need to tweak this value lower/higher to trigger the problem
        name              : "default",
        vhost             : "%2f",
        heartbeat         : 15,
        publishTimeout    : 100,
        replyTimeout      : 2000,
        failAfter         : 60,
        retryLimit        : 10
    }
};

var q_alias = 'foobarqux';

rabbot.configure(options).then(function(ok) {

    // why does rabbot.configure() return a promise?
    // ... the resolving does not imply a usable/valid/a connection or anything else AFAICT
    // the value of `ok` seems meaningless, but is it?

    return rabbot.addQueue(q_alias, {
        durable    : false,
        exclusive  : true,
        noAck      : true,
        noBatch    : true,
        messageTtl : 10000,
        unique     : 'id'
    });

}).then(function(result) {

    // `result` is an instance of "QueueFSM" ? and should it have a name property somewhere?
    console.log('generated queue name is: %s', rabbot.connections.default.definitions.queues[q_alias].uniqueName);

}).catch(function(err) {
    console.error('Promise was REJECTED:', err);
});

// force node to hang about for a bit
setTimeout(function() { console.log('the end.'); }, 10000);
```

### example of output
```
  rabbot.io debug +0ms Attempting acquisition of connection 'default'
  rabbot.connection info +2ms Attempting connection to 'default' (amqp://guest:guest@localhost:5672/%2f?heartbeat=30)
  rabbot.connection info +26ms Failed to connect to 'default' (amqp://guest:guest@localhost:5672/%2f?heartbeat=30) with, 'Error: connect ETIMEDOUT'
  rabbot.connection info +1ms Cannot connect to `default` - all endpoints failed
  rabbot.io error +0ms Acquisition of connection 'default' failed with 'No endpoints could be reached'
  rabbot.topology error +5ms Failed to create reply queue for connection name 'default Error: Failed to create queue 'rosie.node.30925.response.queue' on connection 'default' with 'No endpoints could be reached'
    at .<anonymous> (/scratch/rabbot-test/node_modules/rabbot/src/topology.js:186:10)
    at onConnectionFailed (/scratch/rabbot-test/node_modules/rabbot/src/topology.js:198:13)
    at /scratch/rabbot-test/node_modules/rabbot/src/topology.js:204:6
    at Object.invokeSubscriber (/scratch/rabbot-test/node_modules/monologue.js/lib/monologue.js:181:19)
    at invoker (/scratch/rabbot-test/node_modules/monologue.js/lib/monologue.js:430:11)
    at /scratch/rabbot-test/node_modules/monologue.js/lib/monologue.js:324:5
    at arrayEach (/scratch/rabbot-test/node_modules/monologue.js/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/scratch/rabbot-test/node_modules/monologue.js/node_modules/lodash/index.js:3345:13)
    at /scratch/rabbot-test/node_modules/monologue.js/lib/monologue.js:436:7
    at /scratch/rabbot-test/node_modules/monologue.js/node_modules/lodash/index.js:3073:15
Promise was REJECTED: Error: Failed to create queue 'foobarqux' on connection 'default' with 'No endpoints could be reached'
    at .<anonymous> (/scratch/rabbot-test/node_modules/rabbot/src/topology.js:186:10)
    at onConnectionFailed (/scratch/rabbot-test/node_modules/rabbot/src/topology.js:198:13)
    at /scratch/rabbot-test/node_modules/rabbot/src/topology.js:204:6
    at Object.invokeSubscriber (/scratch/rabbot-test/node_modules/monologue.js/lib/monologue.js:181:19)
    at invoker (/scratch/rabbot-test/node_modules/monologue.js/lib/monologue.js:430:11)
    at /scratch/rabbot-test/node_modules/monologue.js/lib/monologue.js:324:5
    at arrayEach (/scratch/rabbot-test/node_modules/monologue.js/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/scratch/rabbot-test/node_modules/monologue.js/node_modules/lodash/index.js:3345:13)
    at /scratch/rabbot-test/node_modules/monologue.js/lib/monologue.js:436:7
    at /scratch/rabbot-test/node_modules/monologue.js/node_modules/lodash/index.js:3073:15
  rabbot.io debug +2ms Attempting acquisition of connection 'default'
  rabbot.connection info +20ms Attempting connection to 'default' (amqp://guest:guest@localhost:5672/%2f?heartbeat=30)
  rabbot.connection info +9ms Failed to connect to 'default' (amqp://guest:guest@localhost:5672/%2f?heartbeat=30) with, 'Error: connect ETIMEDOUT'
  rabbot.connection info +0ms Cannot connect to `default` - all endpoints failed
  rabbot.io error +1ms Acquisition of connection 'default' failed with 'No endpoints could be reached'
  rabbot.io debug +104ms Attempting acquisition of connection 'default'
  rabbot.connection info +1ms Attempting connection to 'default' (amqp://guest:guest@localhost:5672/%2f?heartbeat=30)
  rabbot.connection info +5ms Connected to 'default' (amqp://guest:guest@localhost:5672/%2f?heartbeat=30)
  rabbot.io debug +0ms Acquired connection 'default' successfully
  rabbot.io debug +4ms Attempting acquisition of channel 'rosie.node.30925.response.queue'
  rabbot.io debug +3ms Attempting acquisition of channel 'rosie.node.30925-foobarqux'
  rabbot.io debug +6ms Acquired channel 'rosie.node.30925.response.queue' successfully
  rabbot.topology info +3ms Declaring queue 'rosie.node.30925.response.queue' on connection 'default' with the options: {"autoDelete":true,"subscribe":true,"uniqueName":"rosie.node.30925.response.queue"}
  rabbot.io debug +3ms Acquired channel 'rosie.node.30925-foobarqux' successfully
  rabbot.topology info +1ms Declaring queue 'rosie.node.30925-foobarqux' on connection 'default' with the options: {"durable":false,"exclusive":true,"noAck":true,"noBatch":true,"messageTtl":10000,"unique":"id","uniqueName":"rosie.node.30925-foobarqux"}
  rabbot.queue info +10ms Starting subscription to queue 'rosie.node.30925.response.queue' on 'default'
the end.
```
as you can see I first log the rejected promise with the message `Failed to create queue 'foobarqux' on connection 'default' with 'No endpoints could be reached'` and later **rabbot** emits the debug message `Declaring queue 'rosie.node.30925-foobarqux' on connection 'default' with the options: `

Am I misunderstanding how to use the module? is there something wrong here? should I use  an older version? how do I wait for an acquired connection before attempting use `addQueue()`? do I need to set `retryLimit` to `0` in order to use the Promise interfaces?

As you can tell I'm a little confused! Any light you could shed on the situation would be very much appreciated!

**Comment by arobson** [comment]
@iamjochem - so a few things seem to be happening:
 1 - I think there's a defect here, after a certain number of retries, it's supposed to stop retrying and let you know it couldn't succeed. At that point, you have the choice to tell it to start trying again _or_ you process.exit (the latter being recommended)
 2 - you're mixing and matching some things: if you want to use configure, use it for all your topology, don't use it for just the connection and then manually call things to add queues and exchanges and all that, use it to define everything at once.
3 - I've not seen the configure promise resolve before when the connection failed, but then I've also never used configure without follow up topology or had a connection timeout set for 5 ms.

I'll see what I can reproduce and go from there. It's been a while since I've had time to work on rabbot so I forget specifically which of these behaviors had test coverage but I'm certain some of them did so I'm surprised at the over-all behavior you're seeing.

**Comment by iamjochem** [comment]
hi @arobson,

thanks for taking a look, hope you can make some headway here (I've been trying to work on a fix myself but I've become a little lost inside the FSMs!)

The reason I use `configure()` is because I do want to set a fixed topology (I do this in my real code, this is the permanent app topology) ... only in this particular instance I want to create a temporary,exclusive queue for the current process (I was making a little cmdline tool for tailing messages sent to our "log" exchange).

AFAICT `configure()` is only a helper to avoid boilerplate code for topology definition, and it uses `addConnection()` underwater, manually adding queues afterwards should just work right? (granted it's not the intention of you API!)

I think the use of `configure()` is a bit of red-herring in the instance, if you try it out with **rabbot** `v1.0.3` you could just use `addConnection()` instead (given that you just fixed that it returns a Promise!)

**Comment by arobson** [comment]
@iamjochem - so after taking a second look at this and testing your code, the problem is that you've set your connection timeout to 5 milliseconds. This is too short and will result in random connection failures so the initial attempt is going to fail more often than not causing the configure promise to reject and your follow up call won't hit because you're only calling the addQueue as part of a success criteria. 

As soon as I remove the connection timeout or up it to something reasonable, the script works as I would expect with the latest version.

You can also move the addQueue outside of the configure call for what it's worth, it doesn't have to come after the configure call, strictly speaking.

**Comment by iamjochem** [comment]
the low timeout was used merely to realiably trigger the error situation. the promise returned by `addQueue()` is being rejects BUT the queue is still being created later ... if you reject the Promise then I do not expect some code to continue trying (and later, possibly succeeding) to create the queue ... a rejected Promise means "queue not created (and queue will not ever be created)" with regard to that particular call to `addQueue()`

to me the issue looks to be that you have an FSM that tries hard/repeatedly to connect and define the queue but expose it via a Promise that gives a binary success/fail status - if the Promise rejected the FSM should be destroyed/shutdown rather than to keep attempting the underlying connection and definition of the queue in question.

**Comment by arobson** [comment]
@iamjochem - ahhh, now I understand. I apologize for misunderstanding your point earlier. Thank you for explaining it.

Unfortunately, the entire premise of `rabbot` is actually built around a set of assumptions:

 1. you are creating a service that requires connectivity to RabbitMQ
 2. if connectivity is lost, it should always be re-established
 3. if connectivity cannot be established or is lost permanently, the service cannot function and should shut down

If you are building anything that does not follow those assumptions, I'm afraid rabbot is going to get in your way. With that in mind, would adding those items to the list of the assumptions at the top of the README help clarify the intent of this library and remove confusion?

**Comment by iamjochem** [comment]
hi,

I don't have a problem with the assumptions, but resolving a Promise like this does not fit your strategy, you are rejecting the Promise but later doing the thing that would have led to the Promise being resolved if it had succeeded straight away.

I would argue that in my test case connectivity could not be established to begin with - this is directly touching your third point AFAICT - so the lib should just shutdown (fail hard), but that is actually not the point here.

having the lib transparently handle temporary connectivity problems is super handy - but I think that the exposed Promises should reflect this ... namely they should not be rejected if the underlying code still intends to do retries ... only when no more attempts will be made should the Promise be rejected.

If I have code that does: 
````js
rabbot.addQueue().then( fn ).catch( otherfn )
``` 
it assumes that `fn` will be called when the queue is successfully created, if `otherfn` is called then I assume **`rabbot`** is telling me that it failed to create the queue ... given that the queue is required I can safely determine that the process should shutdown, even if I ignore the failure (e.g. by not handling the rejecton) my code has no way of knowing that the queue is ever created (and that subsequent/dependent code is now safe to run - i.e. the `fn` then-handle in above example) 

I would argue that this issue needs to be reopened and that the resolution is to change how/when Promises are rejected/resolved so that the resolution reflects what the library is actually doing.

**Comment by iamjochem** [comment]
@arobson - ping, not going to reopen this?
