### ISSUE TITLE
addConnection behaviour changed-cannot listen to emitted events at first connection

### ISSUE THREAD

**Issue by yamii** [arobson/rabbot#29]
I'm using rabbot   `1.0.3` and at first `rabbot.configure`. I didn't get the expected behaviour that I'm used to.

here's my code:
```
// option timeouts where set to higher values
rabbot.configure( options )
.then( () => {
   rabbot.connections.default.on( 'connected', () => {
       -- do something
  } );

  rabbot .connection.default.on( 'closed', function );
  rabbot .connection.default.on( 'unreachable', function );
  rabbot .connection.default.on( 'failed', function );

} )
.catch( ( error ) => {

} );
```
 rabbot was unable to emit an `event` at first connection but  was able to do so when I `restart my RabbitMQ server` ( I think the fix for this issue https://github.com/arobson/rabbot/issues/22 changes the behaviour that I was expecting) 

I can see in the current `addConnection` that we will wait for the connection to emit any event and resolve/reject the promise https://github.com/arobson/rabbot/blob/master/src/index.js#L81. And because of that, I'm unable to listen to any events at first connection hence I was also rejected when rabbit failed to connect which may possible nullify the retryTimeout or xxtimeouts in the configure options. 

while on the reconnection/restart route of RabbitMQ we resolve and return the connection object https://github.com/arobson/rabbot/blob/master/src/index.js#L106. This time I was able to listen to the events. 

Can we retain the previous behaviour? 
I have a PR https://github.com/arobson/rabbot/pull/28 which addresses my issue but I'm not sure if it can affect other functionality that people are used to. I'm open to suggestions on how to rectify this.

Thanks by the way.

**Comment by arobson** [comment]
@yamii - I'm sorry for the breaking change. What do you think of the following?

```js
// note - these events handlers can be attached before the call to configure
rabbot.on( "closed", () => {} );
rabbot.on( "unreachable", () => {} );
rabbot.on( "failed", () => {} );

// option timeouts where set to higher values
rabbot.configure( options )
.then( () => {
  // at this point rabbit is connected, 
  // no need for the additional connection event handler
} )
.catch( ( error ) => {

} );
```

**Comment by yamii** [comment]
@arobson thanks! I didn't know I can do the `rabbot.on` not until now.
