### ISSUE TITLE
drop vagrant in favor of docker, for tests?

### ISSUE THREAD

**Issue by derickbailey** [arobson/rabbot#34]
with the official release of Docker for Windows and Mac, would it make sense to drop the use of Vagrant and just go straight to the RabbitMQ Docker image?

Personally, I was never able to get the Vagrant setup working, to run the tests. However, I have Docker setup and working with RMQ, perfectly fine.

**Comment by arobson** [comment]
@derickbailey - yeah, that's a great suggestion. We've switched to that as well so I can work on that and get that change in place soon since I no longer use the vagrant image on this repo in my tests.

**Comment by arobson** [comment]
@derickbailey done 👍
