### ISSUE TITLE
support generated queue names from RMQ server

### ISSUE THREAD

**Issue by derickbailey** [arobson/rabbot#37]
i'm trying to set up a scenario where I don't care what the queue name is, for a fanout exchange. 

when a consumer connects, it should request a queue without a name, allowing RMQ to generate the name for me.

with the underlying amqplib, this is easy to do. i can omit the name or supply "" for the queue name. the resulting promise tells me the queue name:

```js
channel.assertQueue("").then(function(result){
  console.log(result.queue);
});
```

when providing "" for the queue name in rabbot, however, I don't get a response that is useful. the generated queue name is created, as expected, but the response from the call to `addQueue` appears to be an FSM instance and does not tell me what the queue name is. 

```js
rabbot.addQueue("", {}).then(function(result){
  console.log(result.queue);
});
```

this produces the following console output:

```
{ channel: 
   BehavioralFsm {
     initialState: 'acquiring',
     states: 
      { acquiring: [Object],
        acquired: [Object],
        blocked: [Object],
        closed: [Object],
        failed: [Object],
        releasing: [Object],
        released: [Object] },
     eventListeners: { '*': [] },
     namespace: 'fsm.6',
     useSafeEmit: false,
     hierarchy: {},
     pendingDelegations: {},
     _stamped: true,
     inputQueue: [],
     targetReplayState: 'acquired',
     state: 'acquired',
     priorState: 'acquiring',
     priorAction: 'acquired.operate',
     currentAction: '',
     currentActionArgs: [ [Object], [Object] ],
     inExitHandler: false,
     _cache: 
      { transition: [],
        acquiring: [],
        acquired: [Object],
        handling: [],
        handled: [] },
     rpc: [Function: bound ],
     open: [Function: bound ],
     close: [Function: bound ],
     assertQueue: [Function: bound ],
     checkQueue: [Function: bound ],
     deleteQueue: [Function: bound ],
     purgeQueue: [Function: bound ],
     bindQueue: [Function: bound ],
     unbindQueue: [Function: bound ],
     assertExchange: [Function: bound ],
     checkExchange: [Function: bound ],
     deleteExchange: [Function: bound ],
     bindExchange: [Function: bound ],
     unbindExchange: [Function: bound ],
     publish: [Function: bound ],
     sendToQueue: [Function: bound ],
     consume: [Function: bound ],
     cancel: [Function: bound ],
     get: [Function: bound ],
     ack: [Function: bound ],
     ackAll: [Function: bound ],
     nack: [Function: bound ],
     nackAll: [Function: bound ],
     reject: [Function: bound ],
     prefetch: [Function: bound ],
     recover: [Function: bound ],
     _subscriptions: 
      { acquired: [Object],
        return: [Object],
        released: [Object],
        closed: [Object] },
     item: 
      Channel {
        domain: null,
        _events: [Object],
        _eventsCount: 9,
        _maxListeners: undefined,
        connection: [Object],
        reply: null,
        pending: [],
        lwm: 1,
        unconfirmed: [],
        handleMessage: [Function: acceptDeliveryOrReturn],
        consumers: {},
        ch: 2 },
     waitInterval: 0 },
  messages: 
   { name: '',
     connectionName: 'default',
     resolver: [Function],
     lastAck: -1,
     lastNack: -1,
     lastReject: -1,
     firstAck: undefined,
     firstNack: undefined,
     firstReject: undefined,
     messages: [],
     receivedCount: 0 },
  define: [Function: bound define],
  finalize: [Function: bound finalize],
  getMessageCount: [Function: bound getCount],
  release: [Function: bound release],
  subscribe: [Function: bound subscribe],
  unsubscribe: [Function: bound unsubscribe] }
```

I need to allow randomly generated names and be able to receive the name in the response.

**Comment by arobson** [comment]
@derickbailey ok, now when you get the queue back in the promise, check the `name` property. Keep in mind that for the remainder of that services lifetime you'll keep that same queue name. If you want different behavior, I'll leave that to you to work up in a PR because it'd turn into a major headache to get a brand-new set of machinery every time (and if you didn't have auto-delete random queues, you'd end up with orphaned messages anyway).

I added a test in the integration set that shows how to grab the name. HTH.

**Comment by derickbailey** [comment]
forgive the brain dump, here... i thinking through all of this as i type, editing as i go. let me know if some of this doesn't make sense

### close, but not quite

this is a good step in the right direction, i think.

unfrotunately, it doesn't solve the problem i have where I need more than one generated queue name, at runtime.

when i run this code:

```js
  var options = {};
  return rabbot.addExchange("rabbot.ex.1", "direct", {}).then(() => {
    return rabbot.addQueue("", options).then((q1) => {
      console.log(q1.name);
      return rabbot.addQueue("", options).then((q2) => {
        console.log(q2.name);
        console.log(q1.name === q2.name);
        process.exit();
      });
    });
  });
```

i see that both `q1.name` and `q2.name` are the same - which is what i expected, based on your comment.

### publish-subscribe pattern

the concern comes down to the publish/subscribe pattern, where the subscribers only receive messages if they are connected when the message is published... like events in javascript - only the registered handlers get the event. 

the basic topology in rmq involves a fanout exchange with each app instance that needs the event message, creating it's own queue to receive the message.

i'm only doing this with auto-delete, exclusive queues, of course. that way i don't have orphaned messages stacking up in a queue. 

but i need generated queue names, so i don't end up with multiple app instances trying to consume from the same queue. each process in the pub-sub scenario should receive a copy of the message... i don't want round-robin delivery distributed between consumers.

for now, i have my rabbus project generating my own random queue names using the `uuid` module. i would prefer to let rmq generate the names for me, since that is a core feature of rmq.

### with subscribes for more than one message type

if i have a single "subscriber" scenario in a given application instance, this solution would work. but the moment i need more than one subscriber in an app instance, it falls apart.

say i have a pub/sub for "product" events:

* product.created
* product.updated
* product.deleted

i might have a single app instance listening to all three of these events, but each event type needs to be handled differently. with only a single randomly generated queue name available to me, i am forced to handle all three subscriptions in the same callback.

now add events for "users" and "shopping cart" and a dozen other things. i've suddenly re-created rabbitmq's routing capability in my code.

### on building a pull request for this

i understand the challenge in the current code, due to the way everything is cached. 

i understand the difficulty of re-building the topology when a connection dies and is re-established. you have to listen for the queue name and bind it - every time (even with pre-named queues).

i'll try to find some time to work on a pull request for this... will probably ask a lot of questions when i do find the time!

**Comment by arobson** [comment]
@derickbailey - rabbot already has a solution for your use case without you have to write any more code 😁 Instead of trying to explain it, I'll demonstrate it. I've actually tested the code to make sure it works with the latest version of rabbot.

There are a few other things you could also take advantage of but let's start with the basics:

### publisher
```js
const rabbot = require( "rabbot" );
const _ = require( "lodash" );

var messages = [
    {
      id: 10,
      type: "product.created",
      name: "really great product",
      description: "the bestest thing ever",
      price: 20
    },
    {
      id: 10,
      type: "product.updated",
      price: 25
    },
    {
      id: 10,
      type: "product.deleted"
    }
];

rabbot.handle( "subscriber.ready", () => {
  console.log( "subscriber is ready, sending messages" );
  _.each( messages, ( message ) => {
    rabbot.publish( "commands", { body: message, type: message.type } );
  } );
} );

rabbot.configure( {
  connection: {
    host: "localhost"
  },
  exchanges: [
    {
      name: "commands",
      type: "fanout",
    },
    {
      name: "ready",
      type: "direct"
    }
  ],
  queues: [
    {
      name: "publisher",
      autoDelete: true,
      subscribe: true
    }
  ],
  bindings: [
    {
      exchange: "ready",
      target: "publisher"
    }
  ]
} );
```

### subscriber
```
const rabbot = require( "rabbot" );
const _ = require( "lodash" );

rabbot.handle( "product.created", ( productCreated ) => {
  console.log( "a product was created", productCreated.body );  
} );

rabbot.handle( "product.updated", ( productUpdated ) => {
  console.log( "a product was updated", productUpdated.body );  
} );

rabbot.handle( "product.deleted", ( productDeleted ) => {
  console.log( "a product was deleted", productDeleted.body );  
} );

rabbot.configure( {
  connection: {
    host: "localhost"
  },
  exchanges: [
    {
      name: "commands",
      type: "fanout",
    },
    {
      name: "ready",
      type: "direct"
    }
  ],
  queues: [
    {
      name: "publisher",
      autoDelete: true
    },
    {
      name: "",
      subscribe: true,
      autoDelete: true
    }
  ],
  bindings: [
    {
      exchange: "ready",
      target: "publisher"
    }
  ]
} )
.then( () => {
  return rabbot.addQueue( "", { autoDelete: true, subscribe: true } );
} )
.then( ( queue ) => {
  return rabbot.bindQueue( "commands", queue.name, "#" );
} )
.then( () => {
  console.log( "binding established, sending ready" );
  rabbot.publish( "ready", { type: "subscriber.ready", body: "", routingKey: "" } );
} );
```

**Comment by joelnordell** [comment]
@arobson, in your example above, how would you handle a topology that has multiple fanout exchanges bound to different server-named queues, with different handlers for each such queue?

And, how would your example survive a disconnect/reconnect? Upon reconnect, queues would need to be declared again, giving them new names, then bound to their original exchanges and re-attached to the original handlers -- can that be done using your example here?
