### ISSUE TITLE
console.log maybe not the best choice here...

### ISSUE THREAD

**Issue by djMax** [arobson/rabbot#40]
https://github.com/arobson/rabbot/blob/793ac6a3eec4821eb98ae8a2eeb5993967b63640/src/amqp/queue.js#L332

In our scenario we're bringing the connection up and down and it throws this error sometimes. We handle it fine, but the error in the logs is annoying... Maybe an event instead?

**Comment by arobson** [comment]
@djMax so just removing the `console.log` would clean things up? Honestly I'm thinking I left that in there on accident 😬

**Comment by djMax** [comment]
I figured. :) Thought maybe it was "serious enough" that it warranted a yell so left that choice to you. But yes, removing it would solve my issue.
