### ISSUE TITLE
Improvement suggestion: support for amqplib:purgeQueue command

### ISSUE THREAD

**Issue by kaYcee** [arobson/rabbot#48]
First of all great library! When using it I figured that a particular option would come in very handy, though: having a queue option `purge: true/false` in the topology settings could be used to execute the `channel.purgeQueue(<queue>)` command once the connection has been established. This way an exclusive consumer could make sure that the queue is empty before consuming from it.

**Comment by sallakarppinen** [comment]
Hello, bumping this issue up since I've found myself needing this as well... We have some tests that rely on purging the queues to make sure they start clean. Is there currently any way to do this with rabbot?

**Comment by arobson** [comment]
I've added support for this which I plan to release later today. You can see the docs I added for it here: https://github.com/arobson/rabbot/blob/master/docs/topology.md#rabbotpurgequeue-queuename-connectionname-
