### ISSUE TITLE
Rabbot Connection Failure on Startup doesn't allow for connection without node restart

### ISSUE THREAD

**Issue by PranceTheDeer** [arobson/rabbot#49]
Hey there,

I've been working with this lately to establish some reconnection logic for our message bus.  

So far there's been no issue once rabbot connects, then I attempt reconnects via rabbot.retry() with timeouts in place, works fine no problems.

The issue, is when I start up the app and attempt an initial connection via rabbot.configure and json properties.  

I've tried various methods of reconnecting including: attempting rabbot.retries afterwards, doing rabbot.shutdown followed by an additional rabbot.configure.  Unfortunately neither of these seem to work.  The best scenario I've been able to achieve thus far is rabbot reconnecting but won't pull down any messages.  Even if new ones are added to the queue.  Restarting the node process altogether results in all the messages being pulled down though, even with the same connection settings.  

What method should I be using here in order to get this to work?

Any help would be greatly appreciated.
Thanks

**Comment by PranceTheDeer** [comment]
Just an update here,  I did have some success on connected after using addQueue and startSubscription in order to get the queue message listening again.  The only remaining problem is every attempt to add the exchange in a similar fashion results in "No Endpoints Could be Reached" which is very strange since the queue adding and subscription functions work as intended with the existing connection.

I've even tried adding "default" as the connection name as well as leaving that parameter empty but I'm having no luck.  If this problem could be solved, we'd be all set, but we're stumped honestly.

**Comment by TinOo512** [comment]
@PranceTheDeer Same issue here to mitigate this, I increased the connection timeout.

**Comment by arobson** [comment]
@PranceTheDeer @TinOo512 - I believe this issue is resolved as of 1.0.8 now. I found a problem with how cleanup was taking place that neglected to remove promises for exchange which prevented them from being recreated correctly on reconnection. Let me know if you continue to see this issue with the latest version.
