### ISSUE TITLE
Serialize to JSON if message body is an array

### ISSUE THREAD

**Issue by grimurd** [arobson/rabbot#52]
Was thinking that automatically serialize a message as json when the body of a message is an array wouldn't be the worst idea.

Not exactly difficult to do it manually, but it would be convenient.

**Comment by derickbailey** [comment]
i ran into this as an error recently, and had been meaning to submit an issue about it... it would be nice to support arrays. i think rabbot used to support them (or wascally did)

**Comment by arobson** [comment]
@grimurd @derickbailey - I've added this behavior as of 1.0.8. Let me know if you run into problems with how it works.
