### ISSUE TITLE
rabbit.shutdown() promise never settles

### ISSUE THREAD

**Issue by cascer1** [arobson/rabbot#61]
I'm building a program, and I would like to cleanly shutdown the listener before shutting everything down.

In order, I first shutdown rabbit, then my database connection and then finally exit.

For shutting down, I use the following code:

    console.log("Closing message listener");
    rabbit.shutdown()
      .then(() => {
        console.log("Message listener closed");
        // close database connection
      });

However, the second `console.log` statement is never executed, no matter how long I wait.

Am I doing something wrong or is this a bug?

**Comment by arobson** [comment]
@cascer1 - really odd. Under normal circumstances, the promise returned from shutdown does resolve. Have you established a successful connection in your program at the point you're calling this? I've tested this with a simple program using 1.0.8 and it works reliably.

**Comment by cascer1** [comment]
I do have a connection established (I'm receiving messages), however it's definitely not resolving.

**Comment by arobson** [comment]
@cascer1 - can you share demo so I can repro? The promise resolves in the tests and it resolves in pub/sub demos I've created to try and figure out what you might be running into. Another thing you can also try is setting DEBUG=rabbot.* when starting the service that won't exit. This will result in a _lot_ of output but you might be able to see what's not happening (yeah, that's weird). Shutdown is supposed to:

 1. stop all subscriptions
 2. resolve any remaining messages (ack batching)
 3. close down queue channels once messages are resolved
 4. close down exchange channels
 5. close the connection

You can more or less see all of these things happening in the logs. I'd like to try and find the edge case you're hitting, but I'm not sure how to reproduce it yet.

**Comment by cascer1** [comment]
Thanks for getting back to me. I'll be sure to turn on the debug logging to see what's going on. The project having this issue is [this one](https://github.com/cascer1/diabot), more specifically, [this](https://github.com/cascer1/diabot/blob/master/lib/listener/index.js#L170) and [this](https://github.com/cascer1/diabot/blob/master/lib/worker/index.js#L152) file.

**Comment by cascer1** [comment]
Apologies for my late response. After some further debugging it seems I had the exit handler waiting on *any* of multiple promises to be resolved, instead of all promises. So the program exited as soon as the fastest promise resolved, which was not the rabbit promise.

**Comment by jorgecuesta** [comment]
I have the same issue @arobson here were some message is pending and not just with `shutdown()` also using `closeAll()` or `close(name)`
The only pattern I could check is that if have some message pending to delivery to some subscribe queue/handler it never ends to stop connection/s.
