### ISSUE TITLE
Missing documentation : Queue declaration option "deadLetterRoutingKey"

### ISSUE THREAD

**Issue by iamjochem** [arobson/rabbot#64]
hi @arobson:

rabbot seems to support the "deadLetterRoutingKey" option for queue declarations in addition to the "deadLetter" option ([see here](https://github.com/arobson/rabbot/blob/682cd6bfef75d73e55086e938afe749ea413c641/src/amqp/queue.js#L46)).

the "deadLetterRoutingKey" option is not mentioned in [the docs](https://github.com/arobson/rabbot#addqueue-queuename-options-connectionname-) ... maybe it's worth adding?

kind regards,
Jochem

PS - looks like a couple of lines of [duplicate code (lines 43 & 45) here](https://github.com/arobson/rabbot/blob/682cd6bfef75d73e55086e938afe749ea413c641/src/amqp/queue.js#L42)

**Comment by arobson** [comment]
@iamjochem I added this to the README, thanks. Also - those lines look like dupes, but are supporting all lower case and camel case versions of some of those properties.

**Comment by iamjochem** [comment]
nice one!
