### ISSUE TITLE
No endpoints could be reached?

### ISSUE THREAD

**Issue by jnystrom** [arobson/rabbot#65]
I am using CloudAMQP as an addon to heroku and am getting the `No endpoints could be reached` error.  This does work on previous versions of RabbitMQ/Erlang.  I am not sure what the issue is.  

## works:
RabbitMQ 3.5.7, Erlang 17.5.3

## get error:
RabbitMQ 3.5.8, Erlang 19.1

line that is now failing:
`rabbot.configure({ connection: { uri: this.config.amqp.url } });`
where uri is of `amqp://<user>:<pwd>@<name>.rmq.cloudamqp.com/<user>`

**Comment by arobson** [comment]
@jnystrom - I'm not sure what could be happening. My local environment that I run the tests against uses Rabbit 3.6.5 and Erlang 19.0. To my knowledge, nothing has changed in the AMQP connection string that should cause this. What error are you getting back? I'd need to see the actual protocol error.

**Comment by jnystrom** [comment]
@arobson I apologize.  This seems like something with the instance of my rabbitMQ.  I tried others and everything worked fine.  This is not an issue with rabbot, was an issue with my environment.
