### ISSUE TITLE
WildCard or AMQP type support for messages seems to be broken

### ISSUE THREAD

**Issue by alonisser** [arobson/rabbot#75]
For example If I "rabbit.handle" with a typeName of "*.MyType" or "Api.MyType" and without a specific queue
the actual typeName registered to the handle would be "*.*.MyType" or "*.Api.MyType", which isn't consistent with the way bindings work, suprising to anyone coming from other libraries or docs reference implementation, and I don't really undersand why.
The problem seems to be in index.js "handle method"
```js

if( _.isString( messageType ) ) {
		options = {
			type: messageType,
			queue: queueName || "*",
			context: context,
			autoNack: this.autoNack,
			handler: handler
		}
	} else {
		options = messageType;
		options.autoNack = options.autoNack === false ? false : true;
		options.queue = options.queue || (options.type ? '*' : '#');
		options.handler = options.handler || handler;
	}
	var parts = [];
	if( options.queue === "#" ) {
		parts.push( "#" );
	} else {
		parts.push( options.queue.replace( /[.]/g, "-" ) );
		if( options.type !== "" ) {
			parts.push( options.type || "#" );
		}
	}
```

Bindings do work correctly with this, only handles is broken

**Comment by alonisser** [comment]
Also I found out that messages sent with a name in the wildcard are not handled correctly
For example I logged the nandler to show the topic:
```
topic: '*.CityNotificationIssued',
```
and then got an UnHandled message with the correct routing key
```
warn: Got an unhandled message { fields: 
   { consumerTag: 'someConsumer',
     deliveryTag: 2,
     redelivered: true,
     exchange: 'myExchange',
     routingKey: 'Api.UserNotificationIssued' },
```

**Comment by arobson** [comment]
@alonisser - check this test I've added: https://github.com/arobson/rabbot/blob/master/spec/integration/typeSpecific.spec.js

It demonstrates adding a single type handler for two types without specifying a queue. I have publishes routed so that one goes to each queue and both messages reach the registered handler.

If there's a way to make the documentation clearer, let me know, but this is behaving as designed. Hopefully the test clears up the behavior?

**Comment by alonisser** [comment]
@arobson Thanks, The test does run both on version 1.1.0 (I rewrote it there ) and on 2.0 
Unfortunately we have version 1.0.8 which does not even appear in the tags now
Could this be the problem?

**Comment by arobson** [comment]
@alonisser - yes, most likely it was a defect that got fixed/addressed or was a feature that didn't exist at the time.

This lib has changed *a lot* over time. It does follow semver closely, so the version changes will give you a reliable indication of when there has been a breaking change. 1.0.8 was a very long time ago :)
