### ISSUE TITLE
Request/reply error

### ISSUE THREAD

**Issue by celsomarques** [arobson/rabbot#76]
Hi guys,

I'm facing a problem with request/reply feature. I've two apps, one is the scheduler and the other is the api. I've no control over the order that it's get deployed so in some cases the scheduler starts first and then the api.
When this scenario happens and the scheduler gets reply timeout error and the api responds after reply timeout, I've a lot of messages stuck in nack and my limit goes away very fast.

I hope you can help me with that.
Thanx

**Comment by fifthfloorsoftware** [comment]
Are you using rabbot library in both the handler and the publisher?    We are having a similar problem

**Comment by celsomarques** [comment]
Yes, I was

**Comment by fifthfloorsoftware** [comment]
There are two required fields in order for the reply q to read the pick up on the message.  

The headers must contain a sequence_end field 
And the message properties must contain a correlationId field that is the messageId of the outgoing message. 

Hope that helps

**Comment by celsomarques** [comment]
I'll try that. Thx
