### ISSUE TITLE
Unhandled rejection

### ISSUE THREAD

**Issue by celsomarques** [arobson/rabbot#79]
Hi there,

My app lost its connection to RabbitMQ after a moment and there were no errors before the following message:

> Potentially unhandled rejection [9] Error: Publish failed - no exchange job-message.ex on connection default is defined

How can I handle that?
Does rabbot not able to reconnect automatically?

Thx

**Comment by arobson** [comment]
@celsomarques - publishes return a promise to indicate whether or not they have succeeded, if you don't have a rejection handler, that's going to show up.

The 2.x release I plan to cut later this week will have a slight improvement to publishing. Rabbot does re-establish connections and topologies if you've configured it correctly. I've tested this functionality a lot.

There _are_ limits to what it can do practically though. Check out the doc on (Connection Management)[https://github.com/arobson/rabbot/blob/master/docs/connections.md] to see if it helps clarify the limits and controls you have at your disposal.
