### ISSUE TITLE
Rabbot has insecure dependency

### ISSUE THREAD

**Issue by mcasimir** [arobson/rabbot#82]
Rabbot does not pass the security check from nsp:

```
moment   2.10.2      >=2.11.2   myproject@1.0.0 > rabbot@1.1.0 > whistlepunk@0.3.3 > moment@2.10.2   https://nodesecurity.io/advisories/55 
```

**Comment by arobson** [comment]
I'm somewhat familiar with this issue. It's pretty unlikely that you're going to trigger it but I know the maintainer of whistlepunk and they'd be open to a PR to patch the moment version if it's something you need in order to use rabbot.

**Comment by astanciu** [comment]
There has been a PR submitted to whistlepunk, just been sitting there for almost a year:
https://github.com/LeanKit-Labs/whistlepunk/pull/21

Can we remove this dependency?

**Comment by loayg** [comment]
@arobson @astanciu 
There are 2 vulnerabilities and snyk report has been failing because of these 2 vulnerabilities. 
Also, there is a pr here to update `debug` version: 
https://github.com/arobson/rabbot/pull/110
```
 debug    2.2.0       >= 2.6.9 < 3.0.0 || >= 3.1.0   rabbot@1.1.0 > whistlepunk@0.3.3 > debug@2.2.0     https://nodesecurity.io/advisories/534 
 moment   2.10.2      >=2.11.2              rabbot@1.1.0 > whistlepunk@0.3.3 > moment@2.10.2   https://nodesecurity.io/advisories/55  
```

Thanks.
