### ISSUE TITLE
Request/Reply feature with fanout exchanges

### ISSUE THREAD

**Issue by manixx** [arobson/rabbot#87]
Hey! 

I want to build a *[Scatter Gather](https://stackoverflow.com/questions/23515322/waiting-for-all-rabbitmq-responses-on-a-fanout-exchange)* pattern with rabbitmq and was wondering if the Request/Reply pattern also works with a `fanout` exchanges. 

In short: A message is sent via `request()` to a `fanout` exchange and the callback should get the answer off `all` replies. 
I checked the source and i saw that the message itself contains the `sequence_end: false` but im not able to override this inside the `reply` function:

```
msg.reply({ from: node }, { headers: { sequence_end: false }});
```

I'm aware that this would break the mechanism itself and there are additional steps required to get this working (make the HTTP API call to get the current bindings of the exchange). 

Another approach would be to implement the whole pattern with custom queues and not using the Request/Reply functions, but I was wondering if this is possible. 

Awesome module btw, thanks!

**Comment by arobson** [comment]
@manixx - I've just added this feature for you. You can read the new docs [here](https://github.com/arobson/rabbot/blob/master/docs/publishing.md#scatter-gather).

I hope to cut a release soon that includes this and a few other items.

**Comment by manixx** [comment]
@arobson Thank you very much!
