### ISSUE TITLE
Publishing messages in "bulk"

### ISSUE THREAD

**Issue by nikolayg** [arobson/rabbot#93]
First of all, it's a great library - thanks for your efforts :)

I'd like to publish an array of messages with one operations (i.e. in bulk) and I couldn't see how to do it in the documentation. Does Rabbot support this?

**Comment by arobson** [comment]
@nikolayg - I plan to cut a release later this weekend, but have just finished adding a new feature for this. You can read about it [here](https://github.com/arobson/rabbot/blob/master/docs/publishing.md#rabbotbulkpublish-set-connectionname-).
